name: Basic Workflow
on:
  push:
    branches: feature/basic-workflow
jobs:
  do-things:
    name: Do Things
    runs-on: ubuntu-latest
    steps:
      - name: The Thing I've Done
        run: echo "I've done a thing!"
      - name: oops i did it again
        run: |
          echo "oops i did it again"
          exit 1
